# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Copy the rest of the application code
COPY . .

# Run build
RUN npm run build

# Expose port 3000
EXPOSE 3000

# Start the MCP server using mcp.js as per README instructions
CMD ["node", "dist/mcp.js"]
